MDScreen:
    name:'main'
    MDFloatLayout:
        md_bg_volor : 1,1,1,1
        Image:
            source : 'assets/mergen_logo.jpg'
            pos_hint : {'center_x':0.15, 'center_y':0.95}
            size_hint:.15,.15
        Image:
            source : 'assets/mergen_logo.jpg'
            size_hint: .8, .8
            pos_hint : {'center_x':0.5, 'center_y':0.65}
        MDLabel:
            text: 'H e l l o !'
            font_name: 'BPoppins'
            font_size: '23sp'
            size_hint_x:.85
            pos_hint: {'center_x':.5,'center_y':.38}
            halign: 'center'
            color: rgba(34,34,34,255)
        MDLabel:
            text: 'write something to here!'
            font_name: 'BPoppins'
            font_size: '23sp'
            size_hint_x:.85
            pos_hint: {'center_x':.5,'center_y':.3}
            halign: 'center'
            color: rgba(127,127,127,255)
        Button:
            text:'LOGIN'
            size_hint:.66,.065
            pos_hint: {'center_x':.5,'center_y':.18}
            backround_color:0,0,0,0
            font_name:'BPoppins'
            on_release:
                root.manager.transition.direction = 'left'
                root.manager.current='login'
            canvas.before:
                Color:
                    rgb: rgba(52,0,231,255)
                RoundedRectangle:
                    size: self.size
                    pos: self.pos
                    radius:[5]
        Button:
            text:'SIGNUP'
            size_hint:.66,.065
            pos_hint: {'center_x':.5,'center_y':.09}
            backround_color:0,0,0,0
            font_name:'BPoppins'
            color:rgba(52,0,231,255)
            on_release:
                root.manager.transition.direction = 'left'
                root.manager.current='signup'
            canvas.before:
                Color:
                    rgb: rgba(52,0,231,255)
                Line:
                    width: 1.2
                    rounded_rectangle: self.x,self.y,self.width,self.height, 5,5,5,5,100

