MDScreen:
    name:'signup'
    MDFloatLayout:
        md_bg_color:1,1,1,1
        MDIconButton:
            icon: 'arrow-left'
            pos_hint:{'center_y':.95}
            user_font_size:'30sp'
            theme_text_color:'Custom'
            text_color: rgba(26,24,58,255)
            on_release:
                root.manager.transition.direction = 'right'
                root.manager.current = 'main'
        MDLabel:
            text: 'H i !'
            font_name: 'BPoppins'
            font_size: '26sp'
            pos_hint: {'center_x':.6,'center_y':.95}
            color: rgba(0,0,59,255)
        MDLabel:
            text: 'Create new account'
            font_name: 'MPoppins'
            font_size: '18sp'
            pos_hint: {'center_x':.6,'center_y':.79}
            color: rgba(135,133,193,255)
        MDFloatLayout:
            size_hint:.7,.07
            pos_hint:{'center_x':.5,'center_y':.68}
            TextInput:
                hint_text:'username'
                font_name:'MPoppins'
                size_hint_y:.75
                pos_hint:{'center_x':.43,'center_y':.5}
                backround_color:1,1,1,0
                foreground_color:rgba(0,0,59,255)
                cursor_color:rgba(0,0,59,255)
                font_size:'14sp'
                cursor_width:'2sp'
                multiline:False
            #MDFloatLayout:
             #   pos_hint:{'center_x':.45,'center_y':0}
              #  size_hint_y_:.03
               # md_bg_color:rgba(178,178,178,255)
        MDFloatLayout:
            size_hint:.7,.07
            pos_hint:{'center_x':.5,'center_y':.5}
            TextInput:
                hint_text:'pasword'
                font_name:'MPoppins'
                size_hint_y:.75
                pos_hint:{'center_x':.43,'center_y':.5}
                backround_color:1,1,1,0
                foreground_color:rgba(0,0,59,255)
                cursor_color:rgba(0,0,59,255)
                font_size:'14sp'
                cursor_width:'2sp'
                multiline:False
                pasword:True
            #MDFloatLayout:
             #   pos_hint:{'center_x':.45,'center_y':0}
              #  size_hint_y_:.03
               # md_bg_color:rgba(178,178,178,255)